const TABLE_AVAILABLE = 0;
const TABLE_OPEN = 1;
const PREPARATION_IN_PROGRESS = 2;
const READY_TO_SERVE = 3;
const TABLE_BLOCKED = 4;
const ANOTHER_SERVICE_READY = 5;
const TABLE_LINKED = 6;


const STARTER_COLOR = '#F9D9C9';
const MAIN_COLOR = '#DDD6FC';
const DESSERT_COLOR = '#D1E3F4';
const BEVERAGE_COLOR = '#C5FBF0';

module.exports = {
    TABLE_BLOCKED,
    TABLE_AVAILABLE,
    TABLE_OPEN,
    TABLE_LINKED,
    READY_TO_SERVE,
    PREPARATION_IN_PROGRESS,
    ANOTHER_SERVICE_READY,
    STARTER_COLOR,
    MAIN_COLOR,
    DESSERT_COLOR,
    BEVERAGE_COLOR,
}
